"""initial migration

Revision ID: 6d8e8b250172
Revises: 
Create Date: 2025-03-24 20:52:04.913094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8e8b250172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_plant_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('scientific_name', sa.Text(), nullable=True),
    sa.Column('other_name', sa.Text(), nullable=True),
    sa.Column('cycle', sa.String(length=255), nullable=True),
    sa.Column('watering', sa.String(length=255), nullable=True),
    sa.Column('sunlight', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id')
    )
    op.create_table('planten',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('plant_naam', sa.String(length=100), nullable=False),
    sa.Column('plantensoort', sa.String(length=100), nullable=False),
    sa.Column('plant_geteelt', sa.Boolean(), nullable=True),
    sa.Column('kas_locatie', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('oogsten',
    sa.Column('oogst_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('succesvol', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['planten.plant_id'], ),
    sa.PrimaryKeyConstraint('oogst_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oogsten')
    op.drop_table('users')
    op.drop_table('planten')
    op.drop_table('generic_plant_data')
    # ### end Alembic commands ###
