"""initial migration

Revision ID: 92492ec10489
Revises: 6d8e8b250172
Create Date: 2025-03-24 20:56:34.359170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92492ec10489'
down_revision = '6d8e8b250172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oogsten', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datum', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oogsten', schema=None) as batch_op:
        batch_op.drop_column('datum')

    # ### end Alembic commands ###
