from app import db

class SpecificPlantData(db.Model):
    __tablename__ = "specific_plant_data"

    specific_id = db.Column(db.Integer, primary_key=True)
    plant_id = db.Column(db.Integer, db.ForeignKey("planten.plant_id"))
    family = db.Column(db.String(255))
    origin = db.Column(db.JSON)
    type = db.Column(db.String(255))
    dimension = db.Column(db.String(255))
    dimensions = db.Column(db.JSON)
    cycle = db.Column(db.String(255))
    attracts = db.Column(db.JSON)
    propagation = db.Column(db.JSON)
    hardiness = db.Column(db.JSON)
    watering = db.Column(db.String(255))
    depth_water_requirement = db.Column(db.JSON)
    volume_water_requirement = db.Column(db.JSON)
    watering_general_benchmark = db.Column(db.JSON)
    plant_anatomy = db.Column(db.JSON)
    sunlight = db.Column(db.JSON)
    pruning_month = db.Column(db.JSON)
    pruning_count = db.Column(db.JSON)
    seeds = db.Column(db.Integer)
    maintenance = db.Column(db.String(255))
    care_guides = db.Column("care-guides", db.String(255))
    soil = db.Column(db.JSON)
    growth_rate = db.Column(db.String(255))
    drought_tolerant = db.Column(db.Boolean)
    salt_tolerant = db.Column(db.Boolean)
    thorny = db.Column(db.Boolean)
    invasive = db.Column(db.Boolean)
    tropical = db.Column(db.Boolean)
    indoor = db.Column(db.Boolean)
    care_level = db.Column(db.String(255))
    pest_susceptibility = db.Column(db.JSON)
    pest_susceptibility_api = db.Column(db.String(255))
    flowers = db.Column(db.Boolean)
    flowering_season = db.Column(db.String(255))
    flower_color = db.Column(db.String(255))
    cones = db.Column(db.Boolean)
    fruits = db.Column(db.Boolean)
    edible_fruit = db.Column(db.Boolean)
    edible_fruit_taste_profile = db.Column(db.String(255))
    fruit_nutritional_value = db.Column(db.String(255))
    fruit_color = db.Column(db.JSON)
    harvest_season = db.Column(db.String(255))
    leaf = db.Column(db.Boolean)
    leaf_color = db.Column(db.JSON)
    edible_leaf = db.Column(db.Boolean)
    cuisine = db.Column(db.Boolean)
    medicinal = db.Column(db.Boolean)
    poisonous_to_humans = db.Column(db.Boolean)
    poisonous_to_pets = db.Column(db.Boolean)
    description = db.Column(db.Text)
    default_image = db.Column(db.JSON)
